data_method: MyDataMethodsView.view_test
chart:
  options:
    legend:
      display: true
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Currency Series
      yAxes:
        - scaleLabel:
            display: true
            labelString: Ilość banknotów