data_method: MyDataMethodsView.Note_data_add_note_group_status
#chart:
#  options:
#    scales:
#      xAxes:
#        - stacked: true
#      yAxes:
#        - stacked: true
chart:
  options:
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Creation date
          stacked: true
      yAxes:
        - scaleLabel:
            display: true
            labelString: Note
          stacked: true