data_method: MyDataMethodsView.Note_data_add_to_database
chart:
  options:
    plugins:
      subtitle:
        display: true,
        text: 'WYKRES TESTOWY'
        font:
          family: 'Comic Sans MS'
          size: 20
          weight: 'bold'
          lineHeight: 1.2
      legend:
        position: left
    scales:
      x:
        title:
          display: true
          text: 'Lata'
          color: '#911'
          ticks:
            color: 'red'
        scaleLabel:
          display: true
          labelString: Creation date
#        stacked: true
      y:
        beginAtZero: true
        ticks:
          color: 'green'
        title:
          display: true
          text: 'Ilość Banknotów'
          color: '#200'
          font:
            family: 'Comic Sans MS'
            size: 20
            weight: 'bold'
            lineHeight: 1.2
        scaleLabel:
          display: true
          labelString: Note
#        stacked: true